import Image from 'next/image'
import Link from 'next/link'
import { createAdminClient } from '@/lib/supabase/admin'
import { BriefMarkdown } from '@/components/briefs/BriefMarkdown'
import {
  BriefPrintToolbar,
  PreparedDate,
  ForceLightTheme,
} from '@/components/briefs/BriefPrintToolbar'

/**
 * The opportunity brief as a document — chromeless, printable, and the same
 * text that was read on screen. Reads the STORED brief rather than generating
 * a new one, for the same two reasons the project print view does: a brief
 * carried into a meeting must be the artefact the reader already agreed with,
 * and generation is a 60-90 second local-model call that has no business
 * running inside a print view.
 */

interface PageProps {
  params: Promise<{ id: string }>
}

export async function generateMetadata({ params }: PageProps) {
  const { id } = await params
  const { data: opp } = await createAdminClient()
    .from('opportunities')
    .select('name')
    .eq('id', id)
    .single()
  // The tab title becomes the browser's suggested PDF filename.
  return { title: opp?.name ? `${opp.name} — Brief` : 'Ber Wilson — Brief' }
}

export default async function OpportunityBriefPrintPage({ params }: PageProps) {
  const { id } = await params
  const admin = createAdminClient()

  const [{ data: opp }, { data: briefs }] = await Promise.all([
    admin.from('opportunities').select('name, opp_type, status, location, estimated_value').eq('id', id).single(),
    admin
      .from('stored_briefs')
      .select('content, created_at, metadata')
      .eq('opportunity_id', id)
      .eq('brief_type', 'opportunity')
      .order('created_at', { ascending: false })
      .limit(1),
  ])

  const brief = briefs?.[0]

  if (!opp) {
    return <EmptyState message="That opportunity no longer exists." opportunityId={id} />
  }

  if (!brief) {
    return (
      <EmptyState
        message="No brief has been generated for this opportunity yet. Open the opportunity and choose Generate Brief, then come back."
        opportunityId={id}
      />
    )
  }

  const generated = new Date(brief.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  const stats = (brief.metadata as { stats?: Record<string, number | string | null> } | null)?.stats

  return (
    <div className="min-h-screen bg-white text-slate-900">
      <ForceLightTheme />
      <BriefPrintToolbar backHref={`/opportunities/${id}`} backLabel="Opportunity" text={brief.content} />

      <article className="mx-auto max-w-3xl px-8 py-10 print:py-0">
        <header className="flex items-start justify-between gap-6 pb-5 border-b border-slate-200">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">
              Executive Brief
            </p>
            <h1 className="text-2xl font-semibold mt-1 leading-tight">{opp.name}</h1>
            <p className="text-sm text-slate-500 mt-1">
              Ber Wilson · Generated {generated} · Printed <PreparedDate />
            </p>
            {stats && (
              <p className="text-sm text-slate-700 mt-2 tnum">
                Built from {stats.documents ?? 0} document
                {stats.documents === 1 ? '' : 's'} · {stats.linkedThreads ?? 0} filed and{' '}
                {stats.matchedThreads ?? 0} matched email thread
                {Number(stats.linkedThreads ?? 0) + Number(stats.matchedThreads ?? 0) === 1 ? '' : 's'}
              </p>
            )}
          </div>
          <Image
            src="/logo-light.png"
            alt="Ber Wilson"
            width={640}
            height={339}
            className="object-contain h-9 w-auto"
          />
        </header>

        <div className="mt-6 brief-print">
          <BriefMarkdown text={brief.content} />
        </div>

        <footer className="mt-10 pt-4 border-t border-slate-200 text-xs text-slate-400">
          Generated by Ber Intelligence from platform records, documents and correspondence.
          Figures are as recorded; verify before relying on them externally.
        </footer>
      </article>
    </div>
  )
}

function EmptyState({ message, opportunityId }: { message: string; opportunityId: string }) {
  return (
    <div className="min-h-screen bg-white text-slate-900 flex items-center justify-center p-8">
      <div className="max-w-md text-center">
        <p className="text-sm text-slate-600">{message}</p>
        <Link
          href={`/opportunities/${opportunityId}`}
          className="inline-flex items-center mt-4 h-9 px-3.5 rounded-lg bg-slate-900 text-white text-sm font-medium"
        >
          Back to the opportunity
        </Link>
      </div>
    </div>
  )
}
