/**
 * Deterministic pre-filter — decide what is obviously not deal mail BEFORE the
 * model reads it.
 *
 * Same shape as the filename pass in src/lib/drive/classify.ts: rules first,
 * model only for what is genuinely ambiguous. A thread this rejects is stored
 * (so the filter stays auditable) but settles straight to `skipped`, which
 * costs no model call and is already excluded from clustering and embedding.
 *
 * ⚠ THE RULE SET IS DELIBERATELY ONE RULE LONG, and measuring is why.
 *
 * The obvious candidates for a second rule do not survive contact with the real
 * corpus. Drive "Folder shared with you: Mira Vista - American Fork" was
 * summarised `relevance='deal'` with that deal name; "Invitation: Gov Pointe
 * Teaming USACE" likewise, carrying two attachments. Both look like chrome and
 * both are real signal. Bulk marketing — which IS most of the junk — is handled
 * a layer earlier and for free by Gmail's own `category:promotions` classifier
 * (see mailExclusions), so there is nothing left here worth the risk of
 * swallowing a bid invitation.
 *
 * The bar for adding a rule: it must be impossible for the class to carry deal
 * signal, not merely unlikely.
 */

import {
  allMailboxes,
  LEAD_MAILBOXES,
  PLATFORM_SENDER_NAME,
} from '@/lib/integrations/google-workspace'
import type { ResolvedThread } from '@/lib/integrations/gmail-search'

/** Why a thread was skipped, or null to let the model read it. */
export type PrefilterVerdict = string | null

/**
 * True when the platform itself wrote every message on the thread.
 *
 * The self-loop this closes: the weekly brief, the lead digest and the task
 * digest are sent to LEADS_NOTIFY_EMAIL / team member addresses, which are the
 * same moose@/tuaone@ mailboxes the deal sweep reads — so the platform's own
 * notifications arrive back as deal threads and are summarised as such.
 *
 * EVERY message, not just the first: a human replying to a digest turns it into
 * a real conversation, and that conversation deserves to be read.
 *
 * ⚠ RECOGNISING THE SENDER BY DISPLAY NAME ALONE LET THE LOOP REOPEN, AND THE
 * CHANGE THAT REOPENED IT WAS A GOOD ONE. This matched `from.name ===
 * PLATFORM_SENDER_NAME` ('Ber Intelligence'). On 2026-09-24 Pepper's morning
 * note started sending as *Pepper <info@berwilson.com>* — deliberately, because
 * the first live note arrived as "Ber Intelligence <moose@berwilson.com>",
 * Richard's own address, so his note looked like mail he had sent himself. That
 * fix walked straight through this guard: the name no longer matched, the notes
 * were swept as deal mail, summarised, and had commitments extracted back out
 * of them.
 *
 * Measured 2026-10-09: **131 of 481 open commitments — 27% of the ledger — came
 * from Pepper's own notes**, 24 note threads' worth, compounding every morning
 * because each note listed the previous morning's harvest. 89 of the 131 fuzzy-
 * matched a real obligation already on file and the other 42 were her merged or
 * synthesised lines ("Lock bid scopes for Miller & Midwest and Louisa May
 * Alcott" is one line standing for two bids; "Chase Governor Cox…" is her
 * telling Richard who to chase). None of it was correspondence.
 *
 * So the ADDRESS is now sufficient on its own for the assistant seat, which is
 * structural rather than cosmetic: `LEAD_MAILBOXES` holds info@, Pepper's seat,
 * and that seat is not a person. Whatever display name she signs next cannot
 * reopen this. The platform-name arm stays for everything still sending under
 * it. §12: a vendor's — or our own — display string is not an API contract.
 *
 * The one thing this now also skips is an unanswered outbound message from the
 * assistant seat that reaches a deal mailbox. That is our own words carrying no
 * new deal signal, the lead pipeline owns info@ separately, and the moment
 * anybody replies the `every` above rescues the thread.
 */
function isPlatformMail(thread: ResolvedThread): boolean {
  if (thread.messages.length === 0) return false
  const internal = new Set(allMailboxes().map((m) => m.toLowerCase()))
  const assistantSeat = new Set(LEAD_MAILBOXES.map((m) => m.toLowerCase()))
  return thread.messages.every((m) => {
    const from = m.from
    if (!from) return false
    const address = from.address.toLowerCase()
    if (!internal.has(address)) return false
    return from.name.trim() === PLATFORM_SENDER_NAME || assistantSeat.has(address)
  })
}

/**
 * Classify a freshly fetched thread. Returns a reason to skip, or null to read.
 *
 * Never throws: a pre-filter that can fail would turn a cheap optimisation into
 * a way to lose mail.
 */
export function prefilterThread(thread: ResolvedThread): PrefilterVerdict {
  try {
    // Named rather than generic: "generated by the platform" covers the brief,
    // the digests AND Pepper's note, and when 27% of a ledger turns out to come
    // from one of them, the counter has to say which.
    if (isPlatformMail(thread)) return 'Written by the platform (no human message on the thread)'
    return null
  } catch {
    return null
  }
}
