/**
 * Deterministic pre-filter — decide what is obviously not deal mail BEFORE the
 * model reads it.
 *
 * Same shape as the filename pass in src/lib/drive/classify.ts: rules first,
 * model only for what is genuinely ambiguous. A thread this rejects is stored
 * (so the filter stays auditable) but settles straight to `skipped`, which
 * costs no model call and is already excluded from clustering and embedding.
 *
 * ⚠ THE RULE SET IS DELIBERATELY ONE RULE LONG, and measuring is why.
 *
 * The obvious candidates for a second rule do not survive contact with the real
 * corpus. Drive "Folder shared with you: Mira Vista - American Fork" was
 * summarised `relevance='deal'` with that deal name; "Invitation: Gov Pointe
 * Teaming USACE" likewise, carrying two attachments. Both look like chrome and
 * both are real signal. Bulk marketing — which IS most of the junk — is handled
 * a layer earlier and for free by Gmail's own `category:promotions` classifier
 * (see mailExclusions), so there is nothing left here worth the risk of
 * swallowing a bid invitation.
 *
 * The bar for adding a rule: it must be impossible for the class to carry deal
 * signal, not merely unlikely.
 */

import { allMailboxes, PLATFORM_SENDER_NAME } from '@/lib/integrations/google-workspace'
import type { ResolvedThread } from '@/lib/integrations/gmail-search'

/** Why a thread was skipped, or null to let the model read it. */
export type PrefilterVerdict = string | null

/**
 * True when the platform itself wrote every message on the thread.
 *
 * The self-loop this closes: the weekly brief, the lead digest and the task
 * digest are sent to LEADS_NOTIFY_EMAIL / team member addresses, which are the
 * same moose@/tuaone@ mailboxes the deal sweep reads — so the platform's own
 * notifications arrive back as deal threads and are summarised as such.
 *
 * EVERY message, not just the first: a human replying to a digest turns it into
 * a real conversation, and that conversation deserves to be read. Recognition is
 * by display name AND internal sender together — the name alone could be spoofed
 * from outside, the address alone matches genuine mail between the executives.
 */
function isPlatformMail(thread: ResolvedThread): boolean {
  if (thread.messages.length === 0) return false
  const internal = new Set(allMailboxes().map((m) => m.toLowerCase()))
  return thread.messages.every((m) => {
    const from = m.from
    if (!from) return false
    return from.name.trim() === PLATFORM_SENDER_NAME && internal.has(from.address.toLowerCase())
  })
}

/**
 * Classify a freshly fetched thread. Returns a reason to skip, or null to read.
 *
 * Never throws: a pre-filter that can fail would turn a cheap optimisation into
 * a way to lose mail.
 */
export function prefilterThread(thread: ResolvedThread): PrefilterVerdict {
  try {
    if (isPlatformMail(thread)) return 'Generated by Ber Intelligence'
    return null
  } catch {
    return null
  }
}
