import Image from 'next/image'
import Link from 'next/link'
import { createAdminClient } from '@/lib/supabase/admin'
import { BriefMarkdown } from '@/components/briefs/BriefMarkdown'
import {
  BriefPrintToolbar,
  PreparedDate,
  ForceLightTheme,
} from '@/components/briefs/BriefPrintToolbar'

/**
 * The brief as a document — chromeless, printable, and the same text that was
 * read on screen.
 *
 * Reads the STORED brief rather than generating a new one. Two reasons: a brief
 * carried into a meeting must be the artefact the reader already agreed with,
 * not a fresh one that may say something different; and generation is a 60-90
 * second local-model call that has no business running inside a print view.
 */

interface PageProps {
  params: Promise<{ id: string }>
}

export async function generateMetadata({ params }: PageProps) {
  const { id } = await params
  const { data: project } = await createAdminClient()
    .from('projects')
    .select('name')
    .eq('id', id)
    .single()
  // The tab title becomes the browser's suggested PDF filename.
  return { title: project?.name ? `${project.name} — Brief` : 'Ber Wilson — Brief' }
}

export default async function BriefPrintPage({ params }: PageProps) {
  const { id } = await params
  const admin = createAdminClient()

  const [{ data: project }, { data: briefs }] = await Promise.all([
    admin.from('projects').select('name, sector, stage, location, estimated_value').eq('id', id).single(),
    admin
      .from('stored_briefs')
      .select('content, created_at, metadata')
      .eq('project_id', id)
      .eq('brief_type', 'project')
      .order('created_at', { ascending: false })
      .limit(1),
  ])

  const brief = briefs?.[0]

  if (!project) {
    return <EmptyState message="That project no longer exists." projectId={id} />
  }

  if (!brief) {
    return (
      <EmptyState
        message="No brief has been generated for this project yet. Open the project and choose Generate Brief, then come back."
        projectId={id}
      />
    )
  }

  const generated = new Date(brief.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  const stats = (brief.metadata as { stats?: Record<string, number | string | null> } | null)?.stats

  return (
    <div className="min-h-screen bg-white text-slate-900">
      <ForceLightTheme />
      <BriefPrintToolbar projectId={id} text={brief.content} />

      <article className="mx-auto max-w-3xl px-8 py-10 print:py-0">
        <header className="flex items-start justify-between gap-6 pb-5 border-b border-slate-200">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">
              Executive Brief
            </p>
            <h1 className="text-2xl font-semibold mt-1 leading-tight">{project.name}</h1>
            <p className="text-sm text-slate-500 mt-1">
              Ber Wilson · Generated {generated} · Printed <PreparedDate />
            </p>
            {stats && (
              <p className="text-sm text-slate-700 mt-2 tnum">
                Built from {stats.documents ?? 0} document
                {stats.documents === 1 ? '' : 's'} · {stats.linkedThreads ?? 0} filed and{' '}
                {stats.matchedThreads ?? 0} matched email thread
                {Number(stats.linkedThreads ?? 0) + Number(stats.matchedThreads ?? 0) === 1 ? '' : 's'}
              </p>
            )}
          </div>
          <Image
            src="/logo.png"
            alt="Ber Wilson"
            width={120}
            height={65}
            className="object-contain h-9 w-auto"
          />
        </header>

        <div className="mt-6 brief-print">
          <BriefMarkdown text={brief.content} />
        </div>

        <footer className="mt-10 pt-4 border-t border-slate-200 text-xs text-slate-400">
          Generated by Ber Intelligence from platform records, documents and correspondence.
          Figures are as recorded; verify before relying on them externally.
        </footer>
      </article>
    </div>
  )
}

function EmptyState({ message, projectId }: { message: string; projectId: string }) {
  return (
    <div className="min-h-screen bg-white text-slate-900 flex items-center justify-center p-8">
      <div className="max-w-md text-center">
        <p className="text-sm text-slate-600">{message}</p>
        <Link
          href={`/projects/${projectId}`}
          className="inline-flex items-center mt-4 h-9 px-3.5 rounded-lg bg-slate-900 text-white text-sm font-medium"
        >
          Back to the project
        </Link>
      </div>
    </div>
  )
}
